"""added free_for_members column to events table

Revision ID: 0cbb2788b43b
Revises: 49a415e2b5ee
Create Date: 2023-05-29 19:07:16.511663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cbb2788b43b'
down_revision = '49a415e2b5ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('free_for_members', sa.Boolean(), nullable=True))

    with op.batch_alter_table('signups', schema=None) as batch_op:
        batch_op.drop_column('paid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('free_for_members')

    # ### end Alembic commands ###
