"""moved capacity column back to events table

Revision ID: 112288aec481
Revises: 9030da0f38e4
Create Date: 2023-05-23 15:31:33.885051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112288aec481'
down_revision = '9030da0f38e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity', sa.Integer(), nullable=True))
        batch_op.drop_column('frequency')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('capacity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frequency', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('capacity')

    # ### end Alembic commands ###
