"""altered class table to create class times

Revision ID: 22fe990450d0
Revises: 232270b75f16
Create Date: 2023-05-22 18:42:41.495185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22fe990450d0'
down_revision = '232270b75f16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('time', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_column('time')
        batch_op.drop_column('day')

    # ### end Alembic commands ###
