"""added user to signup relationship

Revision ID: 232270b75f16
Revises: 25828d14831e
Create Date: 2023-05-17 13:36:16.365615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '232270b75f16'
down_revision = '25828d14831e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_payments_customer_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_payments_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('customer_id')

    with op.batch_alter_table('signups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_signups_customer_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_signups_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_signups_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_signups_customer_id_users', 'users', ['customer_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_payments_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_payments_customer_id_users', 'users', ['customer_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
