"""added price category to classes table

Revision ID: 25828d14831e
Revises: 3bdf67ef0cfd
Create Date: 2023-05-16 17:03:32.371045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25828d14831e'
down_revision = '3bdf67ef0cfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
