"""altered classes table

Revision ID: 3bdf67ef0cfd
Revises: 494fbd7058d0
Create Date: 2023-05-16 16:48:32.244643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bdf67ef0cfd'
down_revision = '494fbd7058d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_column('day_of_week')
        batch_op.drop_column('time_of_day')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_of_day', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('day_of_week', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
