"""added description column to memberships table

Revision ID: 494fbd7058d0
Revises: 5e5f7b95911a
Create Date: 2023-05-16 16:42:29.558899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '494fbd7058d0'
down_revision = '5e5f7b95911a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
