"""added to events table

Revision ID: 49a415e2b5ee
Revises: d7181721a8d1
Create Date: 2023-05-25 13:35:36.829069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49a415e2b5ee'
down_revision = 'd7181721a8d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_product_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('stripe_price_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('stripe_price_id')
        batch_op.drop_column('stripe_product_id')

    # ### end Alembic commands ###
