"""added new sessions table and moved columns around

Revision ID: 9030da0f38e4
Revises: b0554a967467
Create Date: 2023-05-23 15:24:27.146983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9030da0f38e4'
down_revision = 'b0554a967467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('day', sa.String(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_sessions_event_id_events')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('day')
        batch_op.drop_column('time')
        batch_op.drop_column('capacity')

    with op.batch_alter_table('signups', schema=None) as batch_op:
        batch_op.drop_constraint('fk_signups_event_id_events', type_='foreignkey')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_signups_event_id_events', 'events', ['event_id'], ['id'])

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('time', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('day', sa.VARCHAR(), nullable=True))

    op.drop_table('sessions')
    # ### end Alembic commands ###
